<?php

namespace App\DataFixtures;

class Creatures {

  public $creatures = [ 
    [
      'id'=> 1,
      'title'=> 'Le Wolpertinger',
      'slug'=> 'wolpertinger',
      'summary'=>
        ' Le Wolpertinger est une créature légendaire de la mythologie bavaroise. Il est souvent décrit comme un animal hybride, résultant de la fusion de différentes espèces. Le terme "Wolpertinger" est dérivé du mot allemand "Wolpertinger" qui signifie "artisan tourneur" en référence à l\'artisanat du bois.',
      'body'=> 
        "Le Wolpertinger est une créature légendaire issue du folklore bavarois. Présentée comme une espèce de chimère, le Wolpertinger est réputé pour sa nature hybride, combinant des caractéristiques d'animaux tels que le lapin, le canard, la chouette et le cerf. Cette curieuse créature fascine depuis longtemps les habitants des régions montagneuses de Bavière, et son image est devenue emblématique de la culture traditionnelle de la région.",
      'picture'=> 'wolpertinger.jpg',
      'other_names'=> ['Oibadrischl', 'Raurackl', 'Rammeschucksn'],
      'related_creatures'=> ['Jackalope', 'Skvader'],
      'size'=> 'de 40 à 60cm de long',
      'weight'=> "jusqu'à 6kg",
      'physical_pecularities'=>
        'Possède diverses formes, des cornes de cerf, des ailes de rapace, des crocs de loup',
      'diet'=> 'Omnivore',
      'localisation'=> 'Alpes bavaroises',
      'origin'=> 'Folklore allemand',
      'first_mention'=> 'XVIème siècle',
      'type_name'=> [1],
      'habitat_name'=> [1],
      'user_id'=> 1,
      'valide'=> true,
      'visible'=> true,
    ],
    [
      'id'=> 2,
      'title'=> 'Le Monstre du Loch Ness',
      'slug'=> 'monstre-du-loch-ness',
      'summary'=>
        'Le Monstre du Loch Ness est une légendaire créature aquatique supposée résider dans le Loch Ness en Écosse, souvent décrite comme un serpent de mer ou un dinosaure aquatique, dont l\'existence n\'a jamais été scientifiquement prouvée.',
      'body'=> 'Le monstre du Loch Ness, également connu sous le nom affectueux de "Nessie", est une créature légendaire qui aurait été aperçue dans les eaux troubles du Loch Ness en Écosse. Considéré comme l\'une des énigmes les plus célèbres et persistantes du monde, le monstre du Loch Ness a suscité l\'intérêt et la curiosité de nombreux chercheurs, explorateurs et amateurs de mystères au fil des décennies.',
      'picture'=> 'loch_ness_monster.jpg',
      'other_names'=> ['Nessie'],
      'related_creatures'=> ['Mokélé-mbembé'],
      'size'=> 'entre 10m et 15m de long',
      'weight'=> 'plusieurs tonnes',
      'physical_pecularities'=>
        "Seule la partie émergée de l'animal a été observée",
      'diet'=> 'Carnivore',
      'localisation'=> 'Loch Ness',
      'origin'=> 'Folklore écossais',
      'first_mention'=> '1898',
      'type_name'=> [5, 6],
      'habitat_name'=> [2],
      'user_id'=> 1,
      'valide'=> true,
      'visible'=> true,
    ],
    [
      'id'=> 3,
      'title'=> 'Le Chupacabra',
      'slug'=> 'chupacabra',
      'summary'=>
        'Le chupacabra est une créature légendaire souvent décrite comme un animal mystérieux, ressemblant à un mélange de reptile et de mammifère, connu pour sucer le sang des animaux domestiques. Sa présence a été signalée principalement en Amérique latine et dans les régions du sud des États-Unis.',
      'body'=> 
        'Le Chupacabra est une créature légendaire qui suscite fascination et crainte depuis de nombreuses années. Aussi connu sous le nom de "chasseur de chèvres", il est souvent associé à des mutilations de bétail et à des attaques sur des animaux domestiques, créant ainsi un mystère entourant son existence. Dans cet article, nous explorerons la légende du Chupacabra, sa description, ses particularités et les témoignages qui ont alimenté les récits populaires.',
      'picture'=> 'chupacabra.jpg',
      'other_names'=> ['El Chupacabra'],
      'related_creatures'=> [],
      'size'=> 'entre 1,2m à 1,5m',
      'weight'=> 'entre 80 et 150kg',
      'physical_pecularities'=>
        'yeux rouges foncés , deux trous pour les narines, une bouche avec des crocs saillants',
      'diet'=> 'Carnivore',
      'localisation'=> 'Amérique latine',
      'origin'=> "Floklore de l'Amérique latine",
      'first_mention'=> 'Incertaine',
      'type_name'=> [1],
      'habitat_name'=> [3, 4],
      'user_id'=> 1,
      'valide'=> true,
      'visible'=> true,
    ],

    [
      'id'=> 4,
      'title'=> 'Le Yéti',
      'slug'=> 'yeti',
      'summary'=>
        "Le yéti, également connu sous le nom d'abominable homme des neiges, est une créature légendaire souvent décrite comme une espèce de grand primate vivant dans les régions montagneuses de l'Himalaya.",
      'body'=> 
        "Le monstre du Yéti, également connu sous le nom d'abominable homme des neiges, est une créature légendaire qui aurait été aperçue dans les régions montagneuses de l'Himalaya. Considéré comme l'un des mystères les plus célèbres et intrigants du monde, le monstre du Yéti a suscité l'intérêt et la fascination de nombreux chercheurs, explorateurs et passionnés de cryptozoologie à travers le temps.",
      'picture' => 'yeti.jpg',
      'other_names'=> [
        'Abominable homme des neiges',
        'Migou',
        'Meh-teh',
        'Dzu-teh',
        'Kang admi',
        'Jobran',
        'Chemo',
        'Teh-lma',
        'Yeh-teh',
      ],
      'related_creatures'=> ['Bigfoot', 'Almasty', 'Yeren', 'Basajaun'],
      'size'=> 'entre 1,5m à 3,75m',
      'weight'=> 'entre 100kg et 200Kg?',
      'physical_pecularities'=> "Epaisse toison le protégeant du froid, visage rappelant étrangement celui d'un humain",
      'diet'=> 'Omnivore',
      'localisation'=> "Asie de l'Est",
      'origin'=> 'Floklore himalayen',
      'first_mention'=> 'IVème siècle av JC',
      'type_name'=> [2],
      'habitat_name'=> [5],
      'user_id'=> 1,
      'valide'=> true,
      'visible'=> true,
    ],
    [
      'id'=> 5,
      'title'=> 'La Bête du Gévaudan',
      'slug'=> 'bete-du-gevaudan',
      'summary'=>
        'La Bête du Gévaudan était une créature légendaire ou un prédateur non identifié qui terrorisa la région du Gévaudan, en France, au XVIIIe siècle. Elle est décrite comme un animal féroce et énorme, responsable de nombreuses attaques mortelles sur les humains, suscitant une peur généralisée et une chasse massive pour la capturer.',
      'body'=> "La Bête du Gévaudan était une créature légendaire qui aurait terrorisé la région du Gévaudan, située dans le sud de la France, pendant une période allant de 1764 à 1767. Cette bête mystérieuse est devenue l'une des figures les plus célèbres du folklore français, et son règne de terreur a captivé l'imagination populaire pendant des siècles. Les attaques brutales et sanglantes attribuées à la Bête ont causé la mort d'un grand nombre de personnes, suscitant la peur et la fascination à travers le pays.",
      'picture'=> 'bete_du_gevaudan.jpg',
      'other_names'=> ['La Bête', 'Le Monstre', 'Le Fléau de Dieu'],
      'related_creatures'=> [''],
      'size'=> '1,5 à 2m',
      'weight'=> 'Entre 120 et 200kg',
      'physical_pecularities'=> "Canidé d'une taille hors norme, large crinière, ne craint pas l'Homme",
      'diet'=>'Carnivore',
      'localisation'=> 'France, Gévaudan',
      'origin'=> "Mythe venant d'une centaine de décès suite à des attaques animales",
      'first_mention'=> '30 juin 1764',
      'type_name'=> [3, 7],
      'habitat_name'=> [1],
      'user_id'=> 1,
      'valide'=> true,
      'visible'=> true,
    ],
    [
      'id'=> 6,
      'title'=> 'Mokélé-mbembé',
      'slug'=> 'mokele-mbembe',
      'summary'=>
        "Le Mokélé-mbembé est une créature légendaire supposée vivre dans les régions reculées des forêts équatoriales d'Afrique, décrite comme une espèce de dinosaure aquatique avec un long cou et un corps massif.",
      'body'=> "Le Mokélé-mbembé est une créature légendaire qui serait présente dans les régions reculées de la République du   Congo et du Cameroun en Afrique centrale. Cette mystérieuse créature a attiré l'attention des explorateurs et des chercheurs du monde entier en raison de sa prétendue nature préhistorique. Le Mokélé-mbembé est souvent décrit comme un reptile aquatique de grande taille, évoquant l'image d'un dinosaure vivant. Son statut de légende et les nombreux témoignages de ceux qui affirment l'avoir aperçu en font un sujet de fascination et de débat.",
      'picture'=> 'mokele_mbembe.jpg',
      'other_names'=> [
        'Mbokäle-muembe',
        'Diba',
        'Songo',
        'Badigui',
        'Ngakoula-ngou',
        'Guanérou',
        'Nyamala',
        'Amali',
      ],
      'related_creatures'=> ['Le Monstre du Loch Ness'],
      'size'=> '7 à 15m de long',
      'weight'=> 'Plusieurs tonnes',
      'physical_pecularities'=> "Taille semblable à l'éléphant, longue queue, long cou, tête reptilienne",
      'diet'=>'Herbivore',
      'localisation'=> 'Centrafrique',
      'origin'=> 'Témoignages coloniaux',
      'first_mention'=> '1913',
      'type_name'=> [5],
      'habitat_name'=> [6, 7],
      'user_id'=> 1,
      'valide'=> true,
      'visible'=> true,
    ],
    [
      'id'=> 7,
      'title'=> 'Le Diable de Jersey',
      'slug'=> 'diable-jersey',
      'summary'=>
        "Le Jersey Devil est une créature légendaire qui aurait ses origines dans les Pinelands du New Jersey, aux États-Unis. Descrite comme une créature mi-humaine, mi-chauve-souris, avec des ailes membraneuses, des cornes et des griffes acérées, le Jersey Devil est souvent associé à des événements surnaturels et continue d'alimenter les récits et les légendes de la région.",
      'body'=> "Le Jersey Devil, également connu sous le nom du Diable de Jersey, est une créature légendaire qui aurait hanté la région des Pine Barrens, dans l'État du New Jersey, aux États-Unis. Cette créature mythique est profondément enracinée dans le folklore local et a captivé l'imagination populaire depuis des générations. Le Jersey Devil est souvent décrit comme une créature hybride, mi-humain, mi-animal, avec des ailes de chauve-souris et des cornes, répandant la terreur dans la région depuis le début du XVIIIe siècle.",
      'picture'=> 'diable_jersey.jpg',
      'other_names'=> ['Jersey Devil', 'Leeds Devil'],
      'related_creatures'=> ['The Dover Demon'],
      'size'=> '1.80m à 2m',
      'weight'=> 'Une centaine de kilos',
      'physical_pecularities'=> 'Corps reptilien, tête de chèvre, sabots fendus et queue fourchue',
      'diet'=> 'Inconnu',
      'localisation'=> 'The Pine Barrens, New Jersey',
      'origin'=> 'Folklore de Philadelphie et du New Jersey',
      'first_mention'=> 'XVIIIème siècle',
      'type_name'=> [4, 1],
      'habitat_name'=> [1, 4],
      'user_id'=> 1,
      'valide'=> true,
      'visible'=> true,
    ],
    [
      'id'=> 8,
      'title'=> "L'Homme-papillon",
      'slug'=> 'homme-papillon',
      'summary'=>
        "Le Mothman est une créature légendaire au corps humanoïde, dotée d'ailes membranées et d'yeux rouges brillants, souvent associée à des événements tragiques et à une atmosphère de prédiction de catastrophes.",
      'body'=> "L'Homme-papillon, également connu sous le nom de Mothman en anglais, est une créature légendaire qui aurait été observée dans la région de Point Pleasant, en Virginie-Occidentale, aux États-Unis, pendant une période de 13 mois entre 1966 et 1967. Cette créature mystérieuse a suscité un grand intérêt parmi les amateurs de phénomènes paranormaux et les passionnés de cryptozoologie. Les témoignages et les rencontres avec l'Homme-papillon ont alimenté la fascination et les spéculations sur son origine et sa signification.",
      'picture'=> 'homme_papillon.jpg',
      'other_names'=> [
        'Homme-phalène',
        'Mothman',
        'Winged Man',
        'Bird Man',
        'UFO-Bird',
        'Mason Bird MOnster',
      ],
      'related_creatures'=> [''],
      'size'=> 'Plus de 2m',
      'weight'=> '60 à 80kg',
      'physical_pecularities'=> 'Mince, mais musculeux, de grandes ailes et des yeux globuleux rougeoyants',
      'diet'=> 'Inconnu',
      'localisation'=> 'Point Pleasant, Virginie-Occidentale',
      'origin'=> 'The Point Pleasant Register, journal local',
      'first_mention'=> 'Novembre 1966',
      'type_name'=> [2, 1],
      'habitat_name'=> [8],
      'user_id'=> 1,
      'valide'=> true,
      'visible'=> true,
    ],
    [
      'id'=> 9,
      'title'=> 'Le Wendigo',
      'slug'=> 'wendigo',
      'summary'=>
      "Le Wendigo est une créature légendaire évoquée dans les traditions des peuples autochtones d'Amérique du Nord, connue pour son apparence effrayante et sa connexion avec la famine et le cannibalisme. Cette créature maigre et affamée, souvent associée à des régions sauvages et froides, inspire fascination et terreur à travers son lien avec le surnaturel et ses capacités surhumaines.",
      'body'=> "Le Wendigo est une créature légendaire issue des traditions des peuples autochtones d'Amérique du Nord. Considéré comme une figure terrifiante, le Wendigo est souvent associé à la famine, à la cannibalisme et à des phénomènes surnaturels. Cette créature fascinante est un personnage récurrent dans les récits et les croyances des cultures autochtones, inspirant à la fois fascination et effroi.",
      'picture'=> 'wendigo.jpg',
      'other_names'=> [
        'Wiindigoo',
        'Wìdjigò',
        'Weendigo',
        'Windago',
        'Windiga',
        'Witiko',
        'Wihtikow',
      ],
      'related_creatures'=> ['Lycanthropes'],
      'size'=> 'Plus de 2m',
      'weight'=> 'Plus de 120kg',
      'physical_pecularities'=> 'Figure humanoïde massive, parfois avec des attributs bestiaux, comme des bois de cerf',
      'diet'=> 'Anthropophage',
      'localisation'=> 'Nord des États-Unis et Canada',
      'origin'=> 'Mythe des Premières Nations algonquiennes',
      'first_mention'=> 'Rapportée en Europe au XVIIème siècle',
      'type_name'=> [4, 2],
      'habitat_name'=> [1],
      'user_id'=> 1,
      'valide'=> true,
      'visible'=> true,
    ],
    [
      'id'=> 10,
      'title'=> 'La Licorne',
      'slug'=> 'licorne',
      'summary'=>
        "La Licorne est une créature légendaire emblématique représentée comme un cheval avec une corne unique sur le front. Symbole de pureté et de magie, la Licorne captive l'imagination avec son allure gracieuse et ses attributs mythiques.",
      'body'=> "La Licorne est une créature légendaire qui a captivé l'imagination des gens à travers les âges. Représentée comme un cheval avec une unique corne en spirale sur le front, la Licorne est souvent associée à la pureté, à la grâce et à la magie. Présente dans les mythologies et les contes populaires du monde entier, la Licorne continue d'exercer une fascination universelle.",
      'picture'=> 'licorne.jpg',
      'other_names'=> ['Unicorne'],
      'related_creatures'=> ['Shâdhavâr', 'Qilin', "Re'em", 'Indrik'],
      'size'=> 'Plus de 1.50m au garrot',
      'weight'=> 'Entre 500 et 800kg',
      'physical_pecularities'=> 'Corne unique au milieu du front',
      'diet'=> 'Herbivore',
      'localisation'=> 'Europe',
      'origin'=> "Récits d'exploration antiques",
      'first_mention'=> 'IVème siècle',
      'type_name'=> [3],
      'habitat_name'=> [1, 9],
      'user_id'=> 1,
      'valide'=> true,
      'visible'=> true,
    ],
    [
      'id'=> 11,
      'title'=> 'Le Phasme Insulaire',
      'slug'=> 'phasme-insulaire',
      'summary'=>
        "Le Phasme Insulaire est une créature fascinante et énigmatique, capable de se camoufler dans son environnement et pouvant atteindre une taille impressionnante pouvant atteindre jusqu'à 5 mètres de long. Doté de capacités psychiques présumées et se trouvant uniquement sur des îlots extrêmement isolés, ce phasme mystérieux intrigue par son potentiel à influencer les rêves, provoquer des hallucinations et peut-être même contrôler mentalement les humains.",
      'body'=> "Le Phasme Insulaire (Phasmus insularis) est une espèce mystérieuse de phasme connue pour sa capacité à se fondre dans son environnement et pour ses caractéristiques uniques. Bien que peu d'informations précises soient disponibles sur cette créature, elle suscite un intérêt considérable en raison de ses particularités énigmatiques et de son potentiel d'influence psychique sur les êtres humains.",
      'picture'=> 'phasme_insulaire.jpg',
      'other_names'=> ['Phasmus insularis', 'The Phasmid'],
      'related_creatures'=> [''],
      'size'=> "Jusqu'à 5m de long",
      'weight'=> 'Inconnu',
      'physical_pecularities'=> "Se fond dans n'importe quel environnement",
      'diet'=> 'Inconnu',
      'localisation'=> 'Îles isolées, partout sur le globe',
      'origin'=> 'Inconnue',
      'first_mention'=> 'XIXème siècle',
      'type_name'=> [8],
      'habitat_name'=> [10],
      'user_id'=> 1,
      'valide'=> true,
      'visible'=> true,
    ],
    [
      'id'=> 12,
      'title'=> 'Le Sasquatch',
      'slug'=> 'sasquatch',
      'summary'=>
        'Le Sasquatch, également connu sous le nom de Bigfoot, est une créature légendaire du folklore nord-américain, souvent décrite comme une grande créature velue ressemblant à un singe qui habiterait les régions sauvages et boisées.',
      'body'=> "Le Sasquatch, également connu sous le nom de Bigfoot, est une créature légendaire du folklore nord-américain qui suscite l'intérêt et la curiosité depuis de nombreuses décennies. Cette mystérieuse créature est souvent associée aux vastes étendues boisées et sauvages de l'Amérique du Nord, où de nombreux témoignages et récits ont contribué à alimenter son mythe. Malgré les recherches et les explorations dédiées à sa recherche, l'existence du Sasquatch reste non prouvée sur le plan scientifique.",
      'picture'=> 'sasquatch.jpg',
      'other_names'=> ['Bigfoot'],
      'related_creatures'=> ['Le Yéti'],
      'size'=> '1.80m à 2.5m',
      'weight'=> '150 à plus de 200kg',
      'physical_pecularities'=> 'Une épaisse toison sur tout le corps, un visage étrangement humain',
      'diet'=> 'Omnivore',
      'localisation'=> 'Canada, Amérique du Nord',
      'origin'=> 'Folklore américain',
      'first_mention'=> 'XVIème siècle',
      'type_name'=> [2],
      'habitat_name'=> [1],
      'user_id'=> 1,
      'valide'=> true,
      'visible'=> true,
    ],
    [
      'id'=> 13,
      'title'=> "L'Olgoï-Khorkhoï",
      'slug'=> 'olgoi-khorkhoi',
      'summary'=>
        "L'Olgoï-Khorkhoï, également appelé ver de la mort, est une créature légendaire d'Asie centrale, souvent décrite comme un ver mortel de couleur rouge vif, vivant dans le désert de Gobi.",
      'body'=> "L'Olgoï-Khorkhoï, également connu sous le nom de ver de la mort, est une créature légendaire qui occupe une place importante dans le folklore d'Asie centrale. Cette énigmatique créature est souvent décrite comme un ver mortel, d'une couleur rouge vif, qui habiterait le désert de Gobi. Bien que les récits et les anecdotes entourant l'Olgoï-Khorkhoï soient nombreux, son existence reste sujette à controverse et n'a jamais été confirmée scientifiquement.",
      'picture'=> 'olgoi-khorkhoi.jpg',
      'other_names'=> ['Ver-intestin', 'Ver de la mort'],
      'related_creatures'=> [''],
      'size'=> "60 à 90 cm de long, diamètre d'environ 20 cm.",
      'weight'=> 'Dans les 600g',
      'physical_pecularities'=> 'Est de couleur sang',
      'diet'=> 'Omnivore',
      'localisation'=> 'Désert de Gobie, Mongolie',
      'origin'=> 'Investigation de Roy Chapman Andrews',
      'first_mention'=> 'XXème siècle',
      'type_name'=> [8],
      'habitat_name'=> [11],
      'user_id'=> 1,
      'valide'=> true,
      'visible'=> true,
    ],
    [
      'id'=> 14,
      'title'=> "L'Oiseau-Tonnerre",
      'slug'=> 'oiseau-tonnerre',
      'summary'=>
        "L'Oiseau-tonnerre est une créature légendaire issue des croyances amérindiennes, particulièrement présente dans les cultures des peuples autochtones des Grandes Plaines et des régions avoisinantes en Amérique du Nord. Souvent décrit comme un gigantesque oiseau doté de plumes resplendissantes et capable de produire des éclairs et du tonnerre, il est associé à des pouvoirs spirituels et à des symboles de force et de protection.",
      'body'=> "L'Oiseau-tonnerre est une créature légendaire d'une grande importance dans les cultures autochtones d'Amérique du Nord. Présente dans les croyances et les récits des peuples autochtones des Grandes Plaines et des régions avoisinantes, cette majestueuse créature ailée est associée à des pouvoirs spirituels et à des symboles de force et de protection. Bien que les interprétations varient selon les différentes tribus, l'Oiseau-tonnerre reste un élément central du riche patrimoine mythologique des peuples autochtones.",
      'picture'=> 'oiseau-tonnerre.jpg',
      'other_names'=> ['Thunderbird'],
      'related_creatures'=> [''],
      'size'=> "De 3 à 5,5m d'envergure",
      'weight'=> "Jusqu'à 25kg",
      'physical_pecularities'=> 'Provoque un bruit semblable au tonnerre par le battement de ses ailes',
      'diet'=> 'Carnivore',
      'localisation'=> 'Îles isolées, partout sur le globe',
      'origin'=> "Mythes des populations amérindiennes d'Amérique du Nord",
      'first_mention'=> 'dès le Xème siècle',
      'type_name'=> [3],
      'habitat_name'=> [3],
      'user_id'=> 1,
      'valide'=> true,
      'visible'=> true,
    ],
  ];

  public $types = [
    [
      'id' => 1,
      'name' => 'Chimère',
    ],
    [
      'id' => 2,
      'name' => 'Humanoïde',
    ],
    [
      'id' => 3,
      'name' => 'Mythique',
    ],
    [
      'id' => 4,
      'name' => 'Occulte',
    ],
    [
      'id' => 5,
      'name' => 'Dinosaure',
    ],
    [
      'id' => 6,
      'name' => 'Aquatique',
    ],
    [
      'id' => 7,
      'name' => 'Animal Sauvage',
    ],
    [
      'id' => 8,
      'name' => 'Insectoïde',
    ]


  ];

  public $habitats = [
    [
      'id' => 1,
      'name' => 'Forêts',
    ],
    [
      'id' => 2,
      'name' => 'Lacustre',
    ],
    [
      'id' => 3,
      'name' => 'Aride',
    ],
    [
      'id' => 4,
      'name' => 'Régions périurbaines',
    ],
    [
      'id' => 5,
      'name' => 'Montagnes',
    ],
    [
      'id' => 6,
      'name' => 'Fleuves',
    ],
    [
      'id' => 7,
      'name' => 'Marais',
    ],
    [
      'id' => 8,
      'name' => 'Inconnu',
    ],
    [
      'id' => 9,
      'name' => 'Prairies reculées',
    ],
    [
      'id' => 10,
      'name' => 'Insulaire',
    ],
    [
      'id' => 11,
      'name' => 'Déserts',
    ]
  ];
};