// eslint-disable-next-line import/no-anonymous-default-export
export default [
    {
      id: 1,
      title: 'Le Wolpertinger',
      slug: 'wolpertinger',
      summary:
        ' Le Wolpertinger est une créature légendaire de la mythologie bavaroise. Il est souvent décrit comme un animal hybride, résultant de la fusion de différentes espèces. Le terme "Wolpertinger" est dérivé du mot allemand "Wolpertinger" qui signifie "artisan tourneur" en référence à l\'artisanat du bois.',
      body: [
        "Le Wolpertinger est une créature légendaire issue du folklore bavarois. Présentée comme une espèce de chimère, le Wolpertinger est réputé pour sa nature hybride, combinant des caractéristiques d'animaux tels que le lapin, le canard, la chouette et le cerf. Cette curieuse créature fascine depuis longtemps les habitants des régions montagneuses de Bavière, et son image est devenue emblématique de la culture traditionnelle de la région.",
        "Description : Le Wolpertinger est décrit comme un animal au corps de lapin, avec des ailes de chauve-souris et des bois de cerf ramifiés. Ses pattes avant ressemblent à celles d'un canard, tandis que ses pattes arrière sont semblables à celles d'un cerf. Il est souvent représenté avec une queue touffue et une tête portant des attributs variés, tels que des plumes, des poils et des yeux globuleux. La taille du Wolpertinger varie généralement entre celle d'un lièvre et celle d'un petit cerf.",
        "Particularités : Le Wolpertinger est souvent associé à des histoires fantastiques et des légendes locales. On dit qu'il habite principalement dans les forêts et les montagnes de Bavière, où il vit dans des terriers souterrains et se déplace avec une grande agilité. Le folklore local attribue au Wolpertinger des pouvoirs magiques et des capacités de métamorphose, lui permettant de se camoufler dans son environnement et d'échapper aux regards indiscrets.",
        'Témoignages : Bien que le Wolpertinger soit généralement considéré comme une créature légendaire, de nombreux témoignages de rencontres avec cette étrange chimère ont été rapportés au fil des ans. Les habitants de la région de Bavière prétendent avoir aperçu le Wolpertinger lors de promenades en forêt ou lors de soirées de chasse. Cependant, ces témoignages sont souvent contradictoires et accompagnés de preuves visuelles peu fiables, telles que des photographies floues ou des traces peu concluantes.',
      ],
      picture: 'src/assets/pictures/wolpertinger.png',
      other_names: ['Oibadrischl', 'Raurackl', 'Rammeschucksn'],
      related_creatures: ['Jackalope', 'Skvader'],
      size: 'de 40 à 60cm de long',
      weight: "jusqu'à 6kg",
      physical_peculiarities:
        'Possède diverses formes, des cornes de cerf, des ailes de rapace, des crocs de loup',
      diet: 'Omnivore',
      localisation: 'Alpes bavaroises',
      origin: 'Folklore allemand',
      first_mention: 'XVIème siècle',
      type_name: ['Chimère'],
      habitat_name: ['Forêts'],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 2,
      title: 'Le Monstre du Loch Ness',
      slug: 'monstre-du-loch-ness',
      summary:
        'Le monstre du Loch Ness est une légende célèbre entourant une prétendue créature aquatique vivant dans le Loch Ness, un lac situé en Écosse',
      body: [
        'Le monstre du Loch Ness, également connu sous le nom affectueux de "Nessie", est une créature légendaire qui aurait été aperçue dans les eaux troubles du Loch Ness en Écosse. Considéré comme l\'une des énigmes les plus célèbres et persistantes du monde, le monstre du Loch Ness a suscité l\'intérêt et la curiosité de nombreux chercheurs, explorateurs et amateurs de mystères au fil des décennies.',
        "Description : La description du monstre du Loch Ness varie selon les témoignages, mais on le décrit généralement comme une créature aquatique de grande taille, ressemblant à un serpent ou à un reptile. Certains rapports suggèrent qu'il pourrait mesurer entre 10 et 15 mètres de long, avec une apparence similaire à celle d'un plésiosaure, un reptile marin préhistorique. Selon ces récits, le monstre du Loch Ness possède un long cou, une tête de forme allongée et une série de bosses ou de bosses sur son dos.",
        "Particularités : Le monstre du Loch Ness est souvent associé à des particularités intrigantes. L'une des caractéristiques les plus notables est sa capacité présumée à échapper à la détection malgré les efforts déployés pour le localiser. Des tentatives de recherche ont été menées au fil des années, utilisant des sonars, des photographies sous-marines et même des plongées en eaux profondes, mais aucune preuve concluante n'a été obtenue. Cette capacité à éviter la capture a alimenté la spéculation selon laquelle le monstre du Loch Ness pourrait être une espèce inconnue, dotée de facultés de camouflage ou de comportements furtifs.",
        "Témoignages : Depuis les premières observations rapportées au début du XXe siècle, de nombreux témoignages de rencontres avec le monstre du Loch Ness ont été enregistrés. Les récits incluent des observations visuelles, des photographies et même des enregistrements sonores prétendument liés à la présence de la créature. Cependant, l'authenticité de ces preuves a souvent été remise en question, et les avis sont partagés quant à la validité des témoignages. Parmi les témoignages les plus célèbres figure la photographie controversée, connue sous le nom de \"Surgeon's Photograph\", prise en 1934 par le chirurgien Robert Kenneth Wilson. Bien que cette photographie ait longtemps été considérée comme une preuve convaincante de l'existence du monstre du Loch Ness, elle a ultérieurement été révélée comme une supercherie. Depuis lors, de nombreuses autres photographies et témoignages ont été présentés, mais la plupart d'entre eux ont été critiqués pour leur manque de clarté ou de fiabilité.",
      ],
      picture: 'src/assets/pictures/loch_ness_monster.png',
      other_names: ['Nessie'],
      related_creatures: ['Mokélé-mbembé'],
      size: 'entre 10m et 15m de long',
      weight: 'plusieurs tonnes',
      physical_peculiarities:
        "Seule la partie émergée de l'animal a été observée",
      diet: 'Carnivore',
      localisation: 'Loch Ness',
      origin: 'Folklore écossais',
      first_mention: '1898',
      type_name: ['Aquatique', 'Dinosaure'],
      habitat_name: ['Lacustre'],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 3,
      title: 'Le Chupacabra',
      slug: 'chupacabra',
      summary:
        'Le chupacabra est une créature légendaire souvent décrite comme un animal mystérieux, ressemblant à un mélange de reptile et de mammifère, connu pour sucer le sang des animaux domestiques. Sa présence a été signalée principalement en Amérique latine et dans les régions du sud des États-Unis.',
      body: [
        'Le Chupacabra est une créature légendaire qui suscite fascination et crainte depuis de nombreuses années. Aussi connu sous le nom de "chasseur de chèvres", il est souvent associé à des mutilations de bétail et à des attaques sur des animaux domestiques, créant ainsi un mystère entourant son existence. Dans cet article, nous explorerons la légende du Chupacabra, sa description, ses particularités et les témoignages qui ont alimenté les récits populaires.',
        "Description : Le Chupacabra est décrit comme une créature bipède mesurant généralement entre 1,2 et 1,5 mètre de hauteur. Son apparence varie selon les témoignages, mais il est souvent décrit comme un hybride étrange entre un reptile et un mammifère. Il possède une peau écailleuse, des griffes acérées et une colonne vertébrale proéminente. Ses yeux sont généralement décrits comme rouges et lumineux, ajoutant une aura de terreur à son image. Certaines descriptions le comparent à un extraterrestre ou à une chimère, renforçant le mystère qui l'entoure.",
        "Particularités : Le Chupacabra est principalement associé à des attaques sur le bétail et les animaux domestiques, où il prélève leur sang de manière presque chirurgicale. Les animaux victimes de ses attaques sont souvent retrouvés avec des marques de morsures et de perforations précises sur le cou, avec peu ou pas de sang restant. Cette particularité a alimenté les spéculations selon lesquelles le Chupacabra serait un prédateur qui se nourrit exclusivement du sang de ses proies. Une autre particularité souvent associée au Chupacabra est son apparente absence de poils ou de plumes, bien que certains témoignages rapportent avoir observé des spécimens avec des poils rares ou des touffes localisées. Les empreintes laissées par la créature sont généralement similaires à celles d'un canidé, mais plus grandes et avec des caractéristiques reptiliennes distinctives.",
        "Témoignages : Les témoignages de rencontres avec le Chupacabra se sont multipliés, principalement en Amérique latine et dans les régions du sud des États-Unis. De nombreuses personnes prétendent avoir aperçu cette créature mystérieuse, et certains prétendent même l'avoir chassée. Malgré cela, aucune preuve concrète de son existence n'a été présentée jusqu'à présent, ce qui a conduit à des débats et à des spéculations quant à sa nature réelle. Certains sceptiques soutiennent que les attaques attribuées au Chupacabra sont en réalité le résultat de prédateurs ordinaires tels que les coyotes ou les chiens errants. Cependant, les caractéristiques spécifiques des attaques, notamment la manière dont le sang est prélevé et les empreintes inhabituelles, continuent de susciter des doutes quant à cette explication.",
      ],
      picture: 'src/assets/pictures/chupacabra.png',
      other_names: ['El Chupacabra'],
      related_creatures: [],
      size: 'entre 1,2m à 1,5m',
      weight: 'entre 80 et 150kg',
      physical_peculiarities:
        'yeux rouges foncés , deux trous pour les narines, une bouche avec des crocs saillants',
      diet: 'Carnivore',
      localisation: 'Amérique latine',
      origin: "Floklore de l'Amérique latine",
      first_mention: 'Incertaine',
      type_name: ['Chimère'],
      habitat_name: ['Régions désertiques', 'Régions périurbaines'],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 4,
      title: 'Le Yéti',
      slug: 'yeti',
      summary:
        "Le yéti, également connu sous le nom d'abominable homme des neiges, est une créature légendaire souvent décrite comme une espèce de grand primate vivant dans les régions montagneuses de l'Himalaya.",
      body: [
        "Le monstre du Yéti, également connu sous le nom d'abominable homme des neiges, est une créature légendaire qui aurait été aperçue dans les régions montagneuses de l'Himalaya. Considéré comme l'un des mystères les plus célèbres et intrigants du monde, le monstre du Yéti a suscité l'intérêt et la fascination de nombreux chercheurs, explorateurs et passionnés de cryptozoologie à travers le temps.",
        "Description : La description du monstre du Yéti varie en fonction des témoignages et des légendes locales. Dans les récits les plus courants, le Yéti est décrit comme une créature de grande taille, similaire à un grand singe ou à un hominidé. On le décrit souvent comme étant recouvert d'une épaisse fourrure brune ou grise pour résister aux conditions extrêmes des régions montagneuses. Le Yéti est généralement décrit comme ayant une silhouette massive, avec de larges épaules et une stature bipède, lui permettant de se déplacer debout.",
        "Particularités : Le monstre du Yéti est souvent associé à certaines particularités intrigantes. L'une des caractéristiques les plus notables est son habitat supposé dans les zones reculées et difficiles d'accès de l'Himalaya, ce qui a rendu les expéditions et les recherches sur le terrain particulièrement complexes. Les témoignages et les légendes suggèrent que le Yéti est bien adapté à la vie en haute altitude et est capable de se déplacer habilement dans des conditions extrêmes. Un autre aspect intéressant est l'existence de traces présumées du Yéti, notamment des empreintes de pas dans la neige ou la boue. Certaines de ces traces ont été collectées au fil des ans, mais leur authenticité a souvent été remise en question. Les moulages et les photographies d'empreintes de pas, bien que parfois intrigants, n'ont pas encore fourni de preuve concluante de l'existence du Yéti.",
        "Témoignages:  Depuis les premiers récits des populations locales de l'Himalaya, de nombreux témoignages de rencontres avec le monstre du Yéti ont été enregistrés. Les témoins prétendent avoir aperçu la créature, parfois de près, lors de leurs expéditions en montagne. Certains affirment avoir vu le Yéti à distance, tandis que d'autres prétendent avoir eu des interactions plus directes avec lui. Cependant, les témoignages varient en termes de détails et de fiabilité, et l'existence du monstre du Yéti reste controversée. Les preuves photographiques et les enregistrements sonores prétendument liés au Yéti ont également été remis en question et soumis à un examen rigoureux. Malgré cela, l'existence possible du Yéti continue de fasciner les explorateurs et les amateurs de mystère, alimentant de nouvelles expéditions et recherches dans les régions montagneuses de l'Himalaya.",
      ],
      picture: 'src/assets/pictures/yeti.png',
      other_names: [
        'Abominable homme des neiges',
        'Migou',
        'Meh-teh',
        'Dzu-teh',
        'Kang admi',
        'Jobran',
        'Chemo',
        'Teh-lma',
        'Yeh-teh',
      ],
      related_creatures: ['Bigfoot', 'Almasty', 'Yeren', 'Basajaun'],
      size: 'entre 1,5m à 3,75m',
      weight: 'entre 100kg et 200Kg?',
      physical_peculiarities:
        "Epaisse toison le protégeant du froid, visage rappelant étrangement celui d'un humain",
      diet: 'Omnivore',
      localisation: "Asie de l'Est",
      origin: 'Floklore himalayen',
      first_mention: 'IVème siècle av JC',
      type_name: ['Humanoïde'],
      habitat_name: ['Montagnes'],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 5,
      title: 'La Bête du Gévaudan',
      slug: 'bete-du-gevaudan',
      summary:
        'La Bête du Gévaudan était une créature légendaire ou un prédateur non identifié qui terrorisa la région du Gévaudan, en France, au XVIIIe siècle. Elle est décrite comme un animal féroce et énorme, responsable de nombreuses attaques mortelles sur les humains, suscitant une peur généralisée et une chasse massive pour la capturer.',
      body: [],
      picture: 'src/assets/pictures/bete_du_gevaudan.png',
      other_names: [],
      related_creatures: [''],
      size: '',
      weight: '',
      physical_peculiarities: '',
      diet: '',
      localisation: '',
      origin: '',
      first_mention: '',
      type_name: [''],
      habitat_name: [''],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 6,
      title: 'Mokélé-mbembé',
      slug: 'mokele-mbembe',
      summary:
        "Le Mokélé-mbembé est une créature légendaire supposée vivre dans les régions reculées des forêts équatoriales d'Afrique, décrite comme une espèce de dinosaure aquatique avec un long cou et un corps massif.",
      body: [],
      picture: 'src/assets/pictures/mokele_mbembe.png',
      other_names: [''],
      related_creatures: [''],
      size: '',
      weight: '',
      physical_peculiarities: '',
      diet: '',
      localisation: '',
      origin: '',
      first_mention: '',
      type_name: [''],
      habitat_name: [''],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 7,
      title: 'Le Diable de Jersey',
      slug: 'diable-jersey',
      summary:
        "Le Jersey Devil est une créature légendaire qui aurait ses origines dans les Pinelands du New Jersey, aux États-Unis. Descrite comme une créature mi-humaine, mi-chauve-souris, avec des ailes membraneuses, des cornes et des griffes acérées, le Jersey Devil est souvent associé à des événements surnaturels et continue d'alimenter les récits et les légendes de la région.",
      body: [],
      picture: 'src/assets/pictures/diable_jersey.png',
      other_names: [''],
      related_creatures: [''],
      size: '',
      weight: '',
      physical_peculiarities: '',
      diet: '',
      localisation: '',
      origin: '',
      first_mention: '',
      type_name: [''],
      habitat_name: [''],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 8,
      title: "L'Homme-papillon",
      slug: 'homme-papillon',
      summary:
        "Le Mothman est une créature légendaire au corps humanoïde, dotée d'ailes membranées et d'yeux rouges brillants, souvent associée à des événements tragiques et à une atmosphère de prédiction de catastrophes.",
      body: [],
      picture: 'src/assets/pictures/homme_papillon.png',
      other_names: ['Homme-phalène', 'Mothman'],
      related_creatures: [''],
      size: '',
      weight: '',
      physical_peculiarities: '',
      diet: '',
      localisation: '',
      origin: '',
      first_mention: '',
      type_name: [''],
      habitat_name: [''],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 1,
      title: 'Le Wolpertinger',
      slug: 'wolpertinger',
      summary:
        ' Le Wolpertinger est une créature légendaire de la mythologie bavaroise. Il est souvent décrit comme un animal hybride, résultant de la fusion de différentes espèces. Le terme "Wolpertinger" est dérivé du mot allemand "Wolpertinger" qui signifie "artisan tourneur" en référence à l\'artisanat du bois.',
      body: [
        "Le Wolpertinger est une créature légendaire issue du folklore bavarois. Présentée comme une espèce de chimère, le Wolpertinger est réputé pour sa nature hybride, combinant des caractéristiques d'animaux tels que le lapin, le canard, la chouette et le cerf. Cette curieuse créature fascine depuis longtemps les habitants des régions montagneuses de Bavière, et son image est devenue emblématique de la culture traditionnelle de la région.",
        "Description : Le Wolpertinger est décrit comme un animal au corps de lapin, avec des ailes de chauve-souris et des bois de cerf ramifiés. Ses pattes avant ressemblent à celles d'un canard, tandis que ses pattes arrière sont semblables à celles d'un cerf. Il est souvent représenté avec une queue touffue et une tête portant des attributs variés, tels que des plumes, des poils et des yeux globuleux. La taille du Wolpertinger varie généralement entre celle d'un lièvre et celle d'un petit cerf.",
        "Particularités : Le Wolpertinger est souvent associé à des histoires fantastiques et des légendes locales. On dit qu'il habite principalement dans les forêts et les montagnes de Bavière, où il vit dans des terriers souterrains et se déplace avec une grande agilité. Le folklore local attribue au Wolpertinger des pouvoirs magiques et des capacités de métamorphose, lui permettant de se camoufler dans son environnement et d'échapper aux regards indiscrets.",
        'Témoignages : Bien que le Wolpertinger soit généralement considéré comme une créature légendaire, de nombreux témoignages de rencontres avec cette étrange chimère ont été rapportés au fil des ans. Les habitants de la région de Bavière prétendent avoir aperçu le Wolpertinger lors de promenades en forêt ou lors de soirées de chasse. Cependant, ces témoignages sont souvent contradictoires et accompagnés de preuves visuelles peu fiables, telles que des photographies floues ou des traces peu concluantes.',
      ],
      picture: 'src/assets/pictures/wolpertinger.png',
      other_names: ['Oibadrischl', 'Raurackl', 'Rammeschucksn'],
      related_creatures: ['Jackalope', 'Skvader'],
      size: 'de 40 à 60cm de long',
      weight: "jusqu'à 6kg",
      physical_peculiarities:
        'Possède diverses formes, des cornes de cerf, des ailes de rapace, des crocs de loup',
      diet: 'Omnivore',
      localisation: 'Alpes bavaroises',
      origin: 'Folklore allemand',
      first_mention: 'XVIème siècle',
      type_name: ['Chimère'],
      habitat_name: ['Forêts'],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 2,
      title: 'Le Monstre du Loch Ness',
      slug: 'monstre-du-loch-ness',
      summary:
        'Le monstre du Loch Ness est une légende célèbre entourant une prétendue créature aquatique vivant dans le Loch Ness, un lac situé en Écosse',
      body: [
        'Le monstre du Loch Ness, également connu sous le nom affectueux de "Nessie", est une créature légendaire qui aurait été aperçue dans les eaux troubles du Loch Ness en Écosse. Considéré comme l\'une des énigmes les plus célèbres et persistantes du monde, le monstre du Loch Ness a suscité l\'intérêt et la curiosité de nombreux chercheurs, explorateurs et amateurs de mystères au fil des décennies.',
        "Description : La description du monstre du Loch Ness varie selon les témoignages, mais on le décrit généralement comme une créature aquatique de grande taille, ressemblant à un serpent ou à un reptile. Certains rapports suggèrent qu'il pourrait mesurer entre 10 et 15 mètres de long, avec une apparence similaire à celle d'un plésiosaure, un reptile marin préhistorique. Selon ces récits, le monstre du Loch Ness possède un long cou, une tête de forme allongée et une série de bosses ou de bosses sur son dos.",
        "Particularités : Le monstre du Loch Ness est souvent associé à des particularités intrigantes. L'une des caractéristiques les plus notables est sa capacité présumée à échapper à la détection malgré les efforts déployés pour le localiser. Des tentatives de recherche ont été menées au fil des années, utilisant des sonars, des photographies sous-marines et même des plongées en eaux profondes, mais aucune preuve concluante n'a été obtenue. Cette capacité à éviter la capture a alimenté la spéculation selon laquelle le monstre du Loch Ness pourrait être une espèce inconnue, dotée de facultés de camouflage ou de comportements furtifs.",
        "Témoignages : Depuis les premières observations rapportées au début du XXe siècle, de nombreux témoignages de rencontres avec le monstre du Loch Ness ont été enregistrés. Les récits incluent des observations visuelles, des photographies et même des enregistrements sonores prétendument liés à la présence de la créature. Cependant, l'authenticité de ces preuves a souvent été remise en question, et les avis sont partagés quant à la validité des témoignages. Parmi les témoignages les plus célèbres figure la photographie controversée, connue sous le nom de \"Surgeon's Photograph\", prise en 1934 par le chirurgien Robert Kenneth Wilson. Bien que cette photographie ait longtemps été considérée comme une preuve convaincante de l'existence du monstre du Loch Ness, elle a ultérieurement été révélée comme une supercherie. Depuis lors, de nombreuses autres photographies et témoignages ont été présentés, mais la plupart d'entre eux ont été critiqués pour leur manque de clarté ou de fiabilité.",
      ],
      picture: 'src/assets/pictures/loch_ness_monster.png',
      other_names: ['Nessie'],
      related_creatures: ['Mokélé-mbembé'],
      size: 'entre 10m et 15m de long',
      weight: 'plusieurs tonnes',
      physical_peculiarities:
        "Seule la partie émergée de l'animal a été observée",
      diet: 'Carnivore',
      localisation: 'Loch Ness',
      origin: 'Folklore écossais',
      first_mention: '1898',
      type_name: ['Aquatique', 'Dinosaure'],
      habitat_name: ['Lacustre'],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 3,
      title: 'Le Chupacabra',
      slug: 'chupacabra',
      summary:
        'Le chupacabra est une créature légendaire souvent décrite comme un animal mystérieux, ressemblant à un mélange de reptile et de mammifère, connu pour sucer le sang des animaux domestiques. Sa présence a été signalée principalement en Amérique latine et dans les régions du sud des États-Unis.',
      body: [
        'Le Chupacabra est une créature légendaire qui suscite fascination et crainte depuis de nombreuses années. Aussi connu sous le nom de "chasseur de chèvres", il est souvent associé à des mutilations de bétail et à des attaques sur des animaux domestiques, créant ainsi un mystère entourant son existence. Dans cet article, nous explorerons la légende du Chupacabra, sa description, ses particularités et les témoignages qui ont alimenté les récits populaires.',
        "Description : Le Chupacabra est décrit comme une créature bipède mesurant généralement entre 1,2 et 1,5 mètre de hauteur. Son apparence varie selon les témoignages, mais il est souvent décrit comme un hybride étrange entre un reptile et un mammifère. Il possède une peau écailleuse, des griffes acérées et une colonne vertébrale proéminente. Ses yeux sont généralement décrits comme rouges et lumineux, ajoutant une aura de terreur à son image. Certaines descriptions le comparent à un extraterrestre ou à une chimère, renforçant le mystère qui l'entoure.",
        "Particularités : Le Chupacabra est principalement associé à des attaques sur le bétail et les animaux domestiques, où il prélève leur sang de manière presque chirurgicale. Les animaux victimes de ses attaques sont souvent retrouvés avec des marques de morsures et de perforations précises sur le cou, avec peu ou pas de sang restant. Cette particularité a alimenté les spéculations selon lesquelles le Chupacabra serait un prédateur qui se nourrit exclusivement du sang de ses proies. Une autre particularité souvent associée au Chupacabra est son apparente absence de poils ou de plumes, bien que certains témoignages rapportent avoir observé des spécimens avec des poils rares ou des touffes localisées. Les empreintes laissées par la créature sont généralement similaires à celles d'un canidé, mais plus grandes et avec des caractéristiques reptiliennes distinctives.",
        "Témoignages : Les témoignages de rencontres avec le Chupacabra se sont multipliés, principalement en Amérique latine et dans les régions du sud des États-Unis. De nombreuses personnes prétendent avoir aperçu cette créature mystérieuse, et certains prétendent même l'avoir chassée. Malgré cela, aucune preuve concrète de son existence n'a été présentée jusqu'à présent, ce qui a conduit à des débats et à des spéculations quant à sa nature réelle. Certains sceptiques soutiennent que les attaques attribuées au Chupacabra sont en réalité le résultat de prédateurs ordinaires tels que les coyotes ou les chiens errants. Cependant, les caractéristiques spécifiques des attaques, notamment la manière dont le sang est prélevé et les empreintes inhabituelles, continuent de susciter des doutes quant à cette explication.",
      ],
      picture: 'src/assets/pictures/chupacabra.png',
      other_names: ['El Chupacabra'],
      related_creatures: [],
      size: 'entre 1,2m à 1,5m',
      weight: 'entre 80 et 150kg',
      physical_peculiarities:
        'yeux rouges foncés , deux trous pour les narines, une bouche avec des crocs saillants',
      diet: 'Carnivore',
      localisation: 'Amérique latine',
      origin: "Floklore de l'Amérique latine",
      first_mention: 'Incertaine',
      type_name: ['Chimère'],
      habitat_name: ['Régions désertiques', 'Régions périurbaines'],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 4,
      title: 'Le Yéti',
      slug: 'yeti',
      summary:
        "Le yéti, également connu sous le nom d'abominable homme des neiges, est une créature légendaire souvent décrite comme une espèce de grand primate vivant dans les régions montagneuses de l'Himalaya.",
      body: [
        "Le monstre du Yéti, également connu sous le nom d'abominable homme des neiges, est une créature légendaire qui aurait été aperçue dans les régions montagneuses de l'Himalaya. Considéré comme l'un des mystères les plus célèbres et intrigants du monde, le monstre du Yéti a suscité l'intérêt et la fascination de nombreux chercheurs, explorateurs et passionnés de cryptozoologie à travers le temps.",
        "Description : La description du monstre du Yéti varie en fonction des témoignages et des légendes locales. Dans les récits les plus courants, le Yéti est décrit comme une créature de grande taille, similaire à un grand singe ou à un hominidé. On le décrit souvent comme étant recouvert d'une épaisse fourrure brune ou grise pour résister aux conditions extrêmes des régions montagneuses. Le Yéti est généralement décrit comme ayant une silhouette massive, avec de larges épaules et une stature bipède, lui permettant de se déplacer debout.",
        "Particularités : Le monstre du Yéti est souvent associé à certaines particularités intrigantes. L'une des caractéristiques les plus notables est son habitat supposé dans les zones reculées et difficiles d'accès de l'Himalaya, ce qui a rendu les expéditions et les recherches sur le terrain particulièrement complexes. Les témoignages et les légendes suggèrent que le Yéti est bien adapté à la vie en haute altitude et est capable de se déplacer habilement dans des conditions extrêmes. Un autre aspect intéressant est l'existence de traces présumées du Yéti, notamment des empreintes de pas dans la neige ou la boue. Certaines de ces traces ont été collectées au fil des ans, mais leur authenticité a souvent été remise en question. Les moulages et les photographies d'empreintes de pas, bien que parfois intrigants, n'ont pas encore fourni de preuve concluante de l'existence du Yéti.",
        "Témoignages:  Depuis les premiers récits des populations locales de l'Himalaya, de nombreux témoignages de rencontres avec le monstre du Yéti ont été enregistrés. Les témoins prétendent avoir aperçu la créature, parfois de près, lors de leurs expéditions en montagne. Certains affirment avoir vu le Yéti à distance, tandis que d'autres prétendent avoir eu des interactions plus directes avec lui. Cependant, les témoignages varient en termes de détails et de fiabilité, et l'existence du monstre du Yéti reste controversée. Les preuves photographiques et les enregistrements sonores prétendument liés au Yéti ont également été remis en question et soumis à un examen rigoureux. Malgré cela, l'existence possible du Yéti continue de fasciner les explorateurs et les amateurs de mystère, alimentant de nouvelles expéditions et recherches dans les régions montagneuses de l'Himalaya.",
      ],
      picture: 'src/assets/pictures/yeti.png',
      other_names: [
        'Abominable homme des neiges',
        'Migou',
        'Meh-teh',
        'Dzu-teh',
        'Kang admi',
        'Jobran',
        'Chemo',
        'Teh-lma',
        'Yeh-teh',
      ],
      related_creatures: ['Bigfoot', 'Almasty', 'Yeren', 'Basajaun'],
      size: 'entre 1,5m à 3,75m',
      weight: 'entre 100kg et 200Kg?',
      physical_peculiarities:
        "Epaisse toison le protégeant du froid, visage rappelant étrangement celui d'un humain",
      diet: 'Omnivore',
      localisation: "Asie de l'Est",
      origin: 'Floklore himalayen',
      first_mention: 'IVème siècle av JC',
      type_name: ['Humanoïde'],
      habitat_name: ['Montagnes'],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 5,
      title: 'La Bête du Gévaudan',
      slug: 'bete-du-gevaudan',
      summary:
        'La Bête du Gévaudan était une créature légendaire ou un prédateur non identifié qui terrorisa la région du Gévaudan, en France, au XVIIIe siècle. Elle est décrite comme un animal féroce et énorme, responsable de nombreuses attaques mortelles sur les humains, suscitant une peur généralisée et une chasse massive pour la capturer.',
      body: [],
      picture: 'src/assets/pictures/bete_du_gevaudan.png',
      other_names: [],
      related_creatures: [''],
      size: '',
      weight: '',
      physical_peculiarities: '',
      diet: '',
      localisation: '',
      origin: '',
      first_mention: '',
      type_name: [''],
      habitat_name: [''],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 6,
      title: 'Mokélé-mbembé',
      slug: 'mokele-mbembe',
      summary:
        "Le Mokélé-mbembé est une créature légendaire supposée vivre dans les régions reculées des forêts équatoriales d'Afrique, décrite comme une espèce de dinosaure aquatique avec un long cou et un corps massif.",
      body: [],
      picture: 'src/assets/pictures/mokele_mbembe.png',
      other_names: [''],
      related_creatures: [''],
      size: '',
      weight: '',
      physical_peculiarities: '',
      diet: '',
      localisation: '',
      origin: '',
      first_mention: '',
      type_name: [''],
      habitat_name: [''],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 7,
      title: 'Le Diable de Jersey',
      slug: 'diable-jersey',
      summary:
        "Le Jersey Devil est une créature légendaire qui aurait ses origines dans les Pinelands du New Jersey, aux États-Unis. Descrite comme une créature mi-humaine, mi-chauve-souris, avec des ailes membraneuses, des cornes et des griffes acérées, le Jersey Devil est souvent associé à des événements surnaturels et continue d'alimenter les récits et les légendes de la région.",
      body: [],
      picture: 'src/assets/pictures/diable_jersey.png',
      other_names: [''],
      related_creatures: [''],
      size: '',
      weight: '',
      physical_peculiarities: '',
      diet: '',
      localisation: '',
      origin: '',
      first_mention: '',
      type_name: [''],
      habitat_name: [''],
      user_id: 1,
      valide: true,
      visible: true,
    },
    {
      id: 8,
      title: "L'Homme-papillon",
      slug: 'homme-papillon',
      summary:
        "Le Mothman est une créature légendaire au corps humanoïde, dotée d'ailes membranées et d'yeux rouges brillants, souvent associée à des événements tragiques et à une atmosphère de prédiction de catastrophes.",
      body: [],
      picture: 'src/assets/pictures/homme_papillon.png',
      other_names: ['Homme-phalène', 'Mothman'],
      related_creatures: [''],
      size: '',
      weight: '',
      physical_peculiarities: '',
      diet: '',
      localisation: '',
      origin: '',
      first_mention: '',
      type_name: [''],
      habitat_name: [''],
      user_id: 1,
      valide: true,
      visible: true,
    },
  ];